name: Run Selenium Script

on:
  # Allow manual triggering
  workflow_dispatch:

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Set up Chrome browser
      uses: browser-actions/setup-chrome@v1

    - name: Run Selenium script
      run: python main2.py
    
    - name: Upload final screenshot
      uses: actions/upload-artifact@v4
      if: always() # This is crucial - it runs even if the previous step fails
      with:
        name: debug-screenshot
        path: debug_screenshot.png

    - name: Verify download
      run: |
        echo "Checking contents of the 'data' directory..."
        ls -l data/

    - name: Commit and push if files changed
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add data/
        # Check if there are any changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit."
        else
          git commit -m "CI: Update downloaded Tableau data"
          git push
        fi